### PR TITLE
#163 incorporate in help files edits from paper

### LINKED ISSUE #163: Incorporate in the help files edits from the stata paper draft
per comment https://github.com/JMSLab/EventStudyPackage/pull/15#issuecomment-1743886479: 
incorporate in the help files edits from the stata paper's command descriptions

### PR DESCRIPTION
**Pull request by Constantino-Carreto-Romero**
Closes #163

### CODE REVIEW

**Comment by jmshapir** [comment]
@Constantino-Carreto-Romero thanks!

Reassigning @jorpppp as reviewer here.

**Comment by jorpppp** [comment]
Thanks @Constantino-Carreto-Romero

I don't want to hold us up here and I can't get to this until late next
week.

Maybe @jorge-emilio-melendez can help us review here with a set of fresh
eyes?

@Constantino-Carreto-Romero can you coordinate with him please?

@jmshapir FYI

**Comment by Constantino-Carreto-Romero** [comment]
@jorge-emilio-melendez 
this is the current paper draft 
[xtevent.pdf](https://github.com/JMSLab/xtevent/files/12833818/xtevent.pdf)
section 3 in the paper should have the same content as in the help files of `xtevent` in this branch.

**Comment by jorge-emilio-melendez** [comment]
I checked that the help files and what the paper says matched each other. It seems that everything is in order.

**Comment by jorpppp** [comment]
Thanks @jorge-emilio-melendez. @Constantino-Carreto-Romero ,can you wrap up and then draft a release, please?

**Pull request merged**
