### PR TITLE
PR for #113: examples without collinearity

### LINKED ISSUE #113: examples without collinearity issues
Change the examples on the homepage, so they don't have collinearity issues

### PR DESCRIPTION
**Pull request by Constantino-Carreto-Romero**
Closes #113

### CODE REVIEW

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero Thanks! Let me just run the test file to make sure everything is OK, and then we can pull.

**Comment by jorpppp** [comment]
I need to check if Jorge Emilio can help checking these examples.

**Comment by jorpppp** [comment]
@jorge-emilio-melendez Will help in reviewing this before merging.

**Comment by jorpppp** [comment]
@jorge-emilio-melendez will review this. But first he'll learn Github, so here are some tasks:

- [ ] Take the intro to Github course: https://github.com/skills/introduction-to-github
- [ ] @Constantino-Carreto-Romero can you point @jorge-emilio-melendez to Jesse's RA guide, please?
- [ ] Run the examples in the readme page: https://github.com/JMSLab/xtevent#readme

**Comment by Constantino-Carreto-Romero** [comment]
Hi @jorge-emilio-melendez, these are the [RA's guide](https://github.com/gslab-econ/lab-manual/wiki/Introduction) and the [workflow guideliness](https://github.com/gslab-econ/lab-manual/wiki/Workflow).

**Comment by jorpppp** [comment]
@jorge-emilio-melendez 's review is pending.

**Comment by jorpppp** [comment]
@jorge-emilio-melendez I couldn't replicate the issue, is this the problematic line?
https://github.com/JMSLab/xtevent/blob/b9ae51e356d14eaee23e6c960f95aaea22f5f37d/test/test.do#L94

**Comment by jorpppp** [comment]
@jorge-emilio-melendez I am not getting that error message. @Constantino-Carreto-Romero , are you getting it?

@jorge-emilio-melendez Can you confirm which version of Stata you are using to test this, please?

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero @jorge-emilio-melendez Since @Constantino-Carreto-Romero  and @jorpppp couldn't replicate this error, we'll chalk it up to something strange @jorge-emilio-melendez did and we'll pull this.

**Review by jorpppp — APPROVED** [review]

**Pull request merged**
