### PR TITLE
PR for #56: check option abbreviations

### LINKED ISSUE #56: Check option abbrevations in all commands
Check option abbreviations in `xtevent`, `xteventplot` and `xteventtest`. Check that all parsers understand the abbreviations and check if we want to enable new abbreviations.

### PR DESCRIPTION
**Pull request by rayhuang11**
Closes #56.

### CODE REVIEW

**Comment by jorpppp** [comment]
Per https://github.com/JMSLab/xtevent/issues/56#issuecomment-1179766956, @rayhuang11 will check a possible option inconsistency with `addabsorb` and `absorb`. Then, @Constantino-Carreto-Romero  will check.

**Comment by rayhuang11** [comment]
@Constantino-Carreto-Romero ready to be checked! My changes are in https://github.com/JMSLab/xtevent/pull/64/commits/b92ecdc0609008bcabf53a7dd60356bb5b06d2db.

**Review by Constantino-Carreto-Romero — COMMENTED** [review]
@jorpppp @rayhuang11 I have reviewed it and I think it is just necessary to update the option's name to `addabsorb` in some other places of the ado files.

**Comment by rayhuang11** [comment]
@Constantino-Carreto-Romero thanks so much for your help!

@jorpppp I've implemented @Constantino-Carreto-Romero's suggested changes. Everything should be working now.

Thanks!

**Comment by rayhuang11** [comment]
@jorpppp thanks for the clarification! I had mistakenly assumed you were only talking about the `addabsorb` option. 

All the abbreviations have been updated in the help file. However, we seem to have a little bit of a problem with the help file for `xteventplot`. Initially, the version in branch` issue 56` did not include the `staticovplotopts` option, so I added it in. However, it seems like the main branch has the option; hence we have a conflict. However, neither the issue 56 subbranch or the main branch have a detailed `{phang`} description for `staticovplotopts`.

Everything else looks fine. So after we make this fix, we can merge.

Fyi @Constantino-Carreto-Romero.

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero will check the conflict, then @jorpppp will review to see if we are ready to merge.

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp @rayhuang11 I have resolved the conflicts. On the other hand, I noticed that the description of the option `staticovplotopts` was interchanged with another option. This had persisted since xtvent 1.0.0 because in that help file it is written the same.

**Pull request merged**
