### PR TITLE
PR for #69: reported mean when imputation

### LINKED ISSUE #69: reported mean in the plot not calculated with the imputed policy variable
Per [comment](https://github.com/JMSLab/xtevent/issues/15#issuecomment-1185027437) in issue #15, when the option `impute` is specified, the reported mean in the plot is not calculated with the imputed version of the policy variable. Also check if the mean calculation follows [comment ](https://github.com/JMSLab/xtevent/issues/15#issuecomment-1185847554)in issue #15.

### PR DESCRIPTION
**Pull request by Constantino-Carreto-Romero**
Closes #69

### CODE REVIEW

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero will run the test file to make sure nothing breaks before merging.

**Comment by jorpppp** [comment]
How are we doing on runing the test file @Constantino-Carreto-Romero ?

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp I didn't find any errors when running the test file after the changes in #69

**Comment by jorpppp** [comment]
Thanks @Constantino-Carreto-Romero , merging now.

**Pull request merged**
