### PR TITLE
#217 Fix results reposting for Sun and Abraham implementation

### LINKED ISSUE #217: Check results reposting for Sun and Abraham implementation
After estimation via Sun and Abraham's method, the coefficients and standard errors are reposted to an xtevent regression, but other elements are not reposted, such as the degrees of freedom. Because of this, some elements of the header in the estimation results after Sun and Abraham estimation are wrong.

### PR DESCRIPTION
**Pull request by jorpppp**
Closes #217

### CODE REVIEW

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero The following returns an error:

```
xtevent y eta , policyvar(z) window(5) vce(cluster i) impute(stag) sunab trend(-3)
```

This error happens because the GMM trend code is trying to adjust the covariance between the other coefficients and the event-time coefficients after adjusting the latter by the trend. The reposting now clears all the other coefficients, so the GMM adjustment code does not find any other coefficients to adjust.

So I think two things need to be fixed:

- If we use Sun Abraham with a trend adjustment, there won't be other coefficients to adjust, and so the code needs to skip the adjustment of the covariance.
- We do not want to drop the other coefficients from the interacted regression away. If you look at how eventstudyinteract works, it only outputs the aggregated event-time coefs in the coefficient table, but it actually keeps the entire e(b) and e(V) from the interacted regression. We want to keep that as well because we may be interested in the coefficients from the interacted regression. We are saving e(b_interact) and e(V_interact) but these do not seem to include the coefficients on eta in the above example.

Can you check this please @Constantino-Carreto-Romero ?

**Comment by Constantino-Carreto-Romero** [comment]
> Thanks @Constantino-Carreto-Romero, this looks good. We are only pending the check about saving the results of the interacted regression. I think e(b) and e(V) should save the aggregates, as we are doing now, such that -test- works on the aggregates, but we need to save the full results from the interacted regression too.

@jorpppp 
in https://github.com/JMSLab/xtevent/pull/219/commits/a3de1002f0e2b2b9ba577f2a02bce12a6ead5ef0 I implemented. The cohort-relative-time interaction variables for the interacted regression were created as temporary variables, so their names were not informative. I recovered the informative names and used them to rename `b` and `V` from the interacted regression as `b_ir` and `V_ir`. Are these names ok? `EventStudyInteract` doesn't rename them and leave them as `b` and `V`, but we cannot use those names because they are reserved for the corrected coefficients and covariance matrix.
When running the following example
```
xtevent y eta , policyvar(z) window(5) vce(cluster i) impute(stag) sunabraham reghdfe savek(aa, saveinteract replace)
mat li e(b_ir)
``` 
I get the following [output](https://github.com/JMSLab/xtevent/assets/36095845/0a54a249-d4f1-4606-b2a0-8deac5a92051).
In https://github.com/JMSLab/xtevent/pull/219/commits/bfc7cb9876e267354b26a404596be602c19604d4 I updated the help file (also changed the order of some related outputs).

**Comment by jorpppp** [comment]
Thank you @Constantino-Carreto-Romero , this looks good. Did you run the test file again after this last change?

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp 
In https://github.com/JMSLab/xtevent/pull/219/commits/c0dee2a3953934dcb4517585a3c91a11cfce518e I updated the test file's log. There were not changes.

**Comment by jorpppp** [comment]
Thank you @Constantino-Carreto-Romero . Merging now.

**Pull request merged**
